export default {
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_AUTH: 'SET_AUTH',
  CLEAR_DATA: 'CLEAR_DATA',
  SET_DATA: 'SET_DATA',
  SET_SENSOR_ID: 'SET_SENSOR_ID',
  SET_ERROR: 'SET_ERROR',
  SET_LOADING: 'SET_LOADING',
  SET_MODAL: 'SET_MODAL',
};
